// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProvaPub.Infra.Data.Context;

#nullable disable

namespace ProvaPub.Infra.Data.Migrations
{
    [DbContext(typeof(TestDbContext))]
    partial class TestDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProvaPub.Domain.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Hubert Legros"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Elisa Walter"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Laverne Rohan"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Gerardo Kuhlman"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Jennie Heaney"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Everett Johnson"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Geneva Stracke"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Harvey Ankunding"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Maxine Stroman"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Allison Parisian"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Terence Jenkins"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Mable Breitenberg"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Carroll Miller"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Benjamin Brekke"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Joanne Schneider"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Randal Hodkiewicz"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Carmen Moen"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Vincent Daniel"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Randy Rowe"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Dora Bartoletti"
                        });
                });

            modelBuilder.Entity("ProvaPub.Domain.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ProvaPub.Domain.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Gorgeous Steel Tuna"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Intelligent Soft Pants"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Sleek Soft Cheese"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Intelligent Rubber Fish"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Tasty Frozen Ball"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Practical Plastic Cheese"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Gorgeous Cotton Hat"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Licensed Rubber Keyboard"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Gorgeous Wooden Bacon"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Fantastic Cotton Towels"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Practical Metal Hat"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Sleek Rubber Bacon"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Refined Steel Table"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Licensed Soft Salad"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Practical Rubber Chair"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Handcrafted Wooden Mouse"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Awesome Soft Sausages"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Licensed Soft Salad"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Unbranded Concrete Hat"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Fantastic Metal Chair"
                        });
                });

            modelBuilder.Entity("ProvaPub.Domain.RandomNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("Numbers");
                });

            modelBuilder.Entity("ProvaPub.Domain.Order", b =>
                {
                    b.HasOne("ProvaPub.Domain.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ProvaPub.Domain.Customer", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
